### PR TITLE
I *think* the missing word was meant to be 'singleton'

### PR DESCRIPTION
**Pull request by pacharanero**
If so please find attached a PR fixing the missing word and with a link to the relevant bit of the doco

### CODE REVIEW

**Comment by davidmiller** [comment]
I think so to! 

However: 
- You've typo'd singleton the second time
-  links should be relative, pointing at markdown files rather than to a specific version of the docs I reckon ?

**Comment by pacharanero** [comment]
good points, well made
I've fixed the typo

Any thought on how best to create a relative link that works for both the compiled docs and the github markdown versions?

**Comment by davidmiller** [comment]
Like this http://www.mkdocs.org/user-guide/writing-your-docs/#linking-documents 
(relative path to the .md file you're targetting)

**Comment by pacharanero** [comment]
Thanks
I've updated the PR accordingly. I haven't attempted to build the docs locally though

**Comment by davidmiller** [comment]
Checked it and it links correctly...

**Pull request merged**
