### PR TITLE
Uplift requests dependency to 2.18.4 and update all references in project

### LINKED ISSUE #1398: Tests fail when using Pipenv for package management due to unpinned dependencies
Using Pipenv, package installation fails due to a conflict with required versions of requests.

Using a virtual environment created using Pipenv, running `python setup.py develop` will see the following package versions installed (generated using `pipenv graph`):

```
opal==0.10.0
  - celery [required: ==3.1.19, installed: 3.1.19]
    - billiard [required: >=3.3.0.21,<3.4, installed: 3.3.0.23]
    - kombu [required: <3.1,>=3.0.29, installed: 3.0.37]
      - amqp [required: >=1.4.9,<2.0, installed: 1.4.9]
      - anyjson [required: >=0.3.3, installed: 0.3.3]
    - pytz [required: >dev, installed: 2017.3]
  - django [required: ==1.10.8, installed: 1.10.8]
  - django-axes [required: ==1.7.0, installed: 1.7.0]
  - django-celery [required: ==3.1.17, installed: 3.1.17]
    - celery [required: >=3.1.15, installed: 3.1.19]
      - billiard [required: >=3.3.0.21,<3.4, installed: 3.3.0.23]
      - kombu [required: <3.1,>=3.0.29, installed: 3.0.37]
        - amqp [required: >=1.4.9,<2.0, installed: 1.4.9]
        - anyjson [required: >=0.3.3, installed: 0.3.3]
      - pytz [required: >dev, installed: 2017.3]
  - django-compressor [required: ==1.5, installed: 1.5]
    - django-appconf [required: >=0.4, installed: 1.0.2]
  - django-reversion [required: ==1.10.2, installed: 1.10.2]
    - django [required: >=1.8, installed: 1.10.8]
  - djangorestframework [required: ==3.4.7, installed: 3.4.7]
  - ffs [required: >=0.0.8.2, installed: 0.0.8.2]
    - six [required: >=1.2.0, installed: 1.11.0]
  - jinja2 [required: ==2.10, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - letter [required: ==0.4.1, installed: 0.4.1]
    - ffs [required: >=0.0.7, installed: 0.0.8.2]
      - six [required: >=1.2.0, installed: 1.11.0]
    - jinja2 [required: Any, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
  - python-dateutil [required: ==2.4.2, installed: 2.4.2]
    - six [required: >=1.5, installed: 1.11.0]
  - requests [required: ==2.7.0, installed: 2.7.0]
  - six [required: >=1.10.0, installed: 1.11.0]
```

If you then run `pipenv install -r test-requirements.txt`, the dependency graph (`pipenv graph`) will look like this: 

```
coveralls==1.2.0
  - coverage [required: >=3.6, installed: 4.4.2]
  - docopt [required: >=0.6.1, installed: 0.6.2]
  - requests [required: >=1.0.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.1.18]
    - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
flake8==3.2.1
  - mccabe [required: >=0.5.0,<0.6.0, installed: 0.5.3]
  - pycodestyle [required: >=2.0.0,<2.3.0, installed: 2.2.0]
  - pyflakes [required: >=0.8.1,<1.4.0,!=1.2.1,!=1.2.2,!=1.2.0, installed: 1.3.0]
mock==2.0.0
  - pbr [required: >=0.11, installed: 3.1.1]
  - six [required: >=1.9, installed: 1.11.0]
opal==0.10.0
  - celery [required: ==3.1.19, installed: 3.1.19]
    - billiard [required: >=3.3.0.21,<3.4, installed: 3.3.0.23]
    - kombu [required: >=3.0.29,<3.1, installed: 3.0.37]
      - amqp [required: >=1.4.9,<2.0, installed: 1.4.9]
      - anyjson [required: >=0.3.3, installed: 0.3.3]
    - pytz [required: >dev, installed: 2017.3]
  - django [required: ==1.10.8, installed: 1.10.8]
  - django-axes [required: ==1.7.0, installed: 1.7.0]
  - django-celery [required: ==3.1.17, installed: 3.1.17]
    - celery [required: >=3.1.15, installed: 3.1.19]
      - billiard [required: >=3.3.0.21,<3.4, installed: 3.3.0.23]
      - kombu [required: >=3.0.29,<3.1, installed: 3.0.37]
        - amqp [required: >=1.4.9,<2.0, installed: 1.4.9]
        - anyjson [required: >=0.3.3, installed: 0.3.3]
      - pytz [required: >dev, installed: 2017.3]
  - django-compressor [required: ==1.5, installed: 1.5]
    - django-appconf [required: >=0.4, installed: 1.0.2]
  - django-reversion [required: ==1.10.2, installed: 1.10.2]
    - django [required: >=1.8, installed: 1.10.8]
  - djangorestframework [required: ==3.4.7, installed: 3.4.7]
  - ffs [required: >=0.0.8.2, installed: 0.0.8.2]
    - six [required: >=1.2.0, installed: 1.11.0]
  - jinja2 [required: ==2.10, installed: 2.10]
    - MarkupSafe [required: >=0.23, installed: 1.0]
  - letter [required: ==0.4.1, installed: 0.4.1]
    - ffs [required: >=0.0.7, installed: 0.0.8.2]
      - six [required: >=1.2.0, installed: 1.11.0]
    - jinja2 [required: Any, installed: 2.10]
      - MarkupSafe [required: >=0.23, installed: 1.0]
  - python-dateutil [required: ==2.4.2, installed: 2.4.2]
    - six [required: >=1.5, installed: 1.11.0]
  - requests [required: ==2.7.0, installed: 2.18.4]
    - certifi [required: >=2017.4.17, installed: 2018.1.18]
    - chardet [required: <3.1.0,>=3.0.2, installed: 3.0.4]
    - idna [required: >=2.5,<2.7, installed: 2.6]
    - urllib3 [required: <1.23,>=1.21.1, installed: 1.22]
  - six [required: >=1.10.0, installed: 1.11.0]
```

`requests` has been bumped to the latest version, likely due to it being an unpinned dependency for `coveralls`

This now means that `opal test` complains about the version of `requests` installed as it does not match that specified in `setup.py`.

This seems due to difference in behaviour between `pip` and `pipenv`: 
- `pip` ensures that a minimum dependency version is met, and will not update an installed package if it already meets that requirement; 
- `pipenv` will take a minimum dependency to mean 'latest version that meets the requirement' and will upgrade an existing installed package regardless of whether it already meets the requirement.

*Note: If you're testing this out yourself, dont forget to remove the Pipfiles before you test each scenario!*

Options

1. **Bump `requests` version in setup.py to the latest version and pin test-requirements.txt to the same version** - will have to make sure tests still run and review change list etc.

2. **Pin the `requests` version in test-requirements.txt to version 2.7.0** - should just continue to function as currently, but will ensure the correct version is installed when using tools like Pipenv

3. **Do 1 or 3 PLUS start including a Pipfile in the repo alongside test-requirements.txt** and update the guidance to either use `pip install -r test-requirements.txt` or `pipenv install --dev` depending on which environment tool people are using. Downside - both dependency files will need maintaining for the forseeable future.

4. **Don't care about Pipenv** - would probably be fine for the moment, but would be worth putting something specific in docs to say this. Also should consider growing use of Pipenv.

If versions are not pinned in both places, there is a chance that this will just occur again when a new version of requests is released. 

Pipenv is not intended to replace setup.py (as Pipenv is for development workflow, setup.py is for packages) so whichever option is chosen, it probably involves pinning dependencies in both setup.poy and dev dependencies.

### PR DESCRIPTION
**Pull request by mattstibbs**
- Updates the setup.py dependency for `requests` to 2.18.4
- Adds `requests` as a pinned dependency in test-requirements.txt

Change history https://github.com/requests/requests/blob/v2.18.4/HISTORY.rst

This closes #1398 with 'Option 2'

### CODE REVIEW

**Comment by mattstibbs** [comment]
`requests` change history (https://github.com/requests/requests/blob/v2.18.4/HISTORY.rst)

**Comment by davidmiller** [comment]
Nice :) 

Apart from one of us reviewing the changelog, I think before merging we'd want to note the upgrade in:
* 0.10.0 [Changelog](https://github.com/openhealthcare/opal/blob/v0.10.0/CHANGELOG.md#updates-to-the-dependency-graph)
* 0.9.x -> 0.10.0 [Upgrade guide](https://github.com/openhealthcare/opal/blob/v0.10.0/doc/docs/reference/upgrading.md#091---0100)

**Comment by mattstibbs** [comment]
@davidmiller added to the docs and scaffolded requirements.txt

Also did a quick search to make sure no other references to 2.7.0

**Comment by davidmiller** [comment]
LGTM - thanks ! 

Requests HISTORY.rst is (somewhat unsurprisingly) updates to certs and dependencies plus sequences of minor changes to advanced features that I don't think we're even pretending to use.

**Pull request merged**
