### PR TITLE
619 created timestamp in bulk update

### PR DESCRIPTION
**Pull request by davidmiller**

### CODE REVIEW

**Comment by fredkingham** [comment]
I'm not sure this is right. I'm not sure we should be updating created without created by, we should also have an option for updated and updated by.

If we used update_from_dict whenever we updated episode both of these issues would be fixed. 

This is probably preferable but creates a lot more work.

**Comment by davidmiller** [comment]
I don't think updated/created and updated_by/created_by are related.
I don't think I ever don't want created/updated set.
I'd be more open to considering it wrong because it should be auto_now / auto_now_add.

> I'm not sure we should be updating created without created by 
Why not?

> If we used update_from_dict whenever we updated episode both of these issues would be fixed.
I'm not sure I know what this means... 

This PR addresses this ticket: https://github.com/openhealthcare/opal/issues/619 
There are occasions when it might make sense to not have a user. 
There are no occasions when we don't want timestamps.

**Comment by davidmiller** [comment]
@fredkingham If you've decided not to merge this then let's close it ?

**Comment by fredkingham** [comment]
I'm closing this, given 
https://github.com/openhealthcare/opal/issues/1347 and  https://github.com/openhealthcare/opal/issues/1353

**Pull request closed without merging**
