### PR TITLE
Smallscreen friendly

### PR DESCRIPTION
**Pull request by davidmiller**
This is a stacked Pull Request which relies on #556 

This includes some early quick wins for smaller or touch devices.

We make the top level application menu more compact, tweak the modal styles, present an alternative patient list view, and show all the add/edit buttons in detail view.

### CODE REVIEW

**Comment by GabPoll** [comment]
no idea if appropriate for me to comment here, but the list of commits seems perfectly sensible.

**Comment by michaeledwardmarks** [comment]
Si.
I was looking using a Google Nexus 7 - 7 inch screen and screen use optimisation seems good plan!

**Comment by GabPoll** [comment]
interesting point @michaeledwardmarks . We need to have an idea of the most likely target screen. In essence, is this going to be an iPad driven exercise because that is all the Trust will allow.

Personally, 7' tablet = portrait (basically a mobile phone), whereas 10"+ = landscape = tablet-like interface.

**Comment by michaeledwardmarks** [comment]
Well I think 7 is quite a bit bigger than many phones (4-6) but agree at the small end for tablets - was just testing as I have 22 Nexus 7s in my office. 
Not sure what size an iPad mini is...

**Comment by GabPoll** [comment]
i think iPad mini 8". 

Aspect ratio of screens important too I guess. 16:9 pushes you to landscape. 4:3 (iPad) or 3:2 (Surface) more flexible. 

Anyway, just some vague things to consider. Commits above relevant largely irrespective of screen sizes at this stage.

**Comment by davidmiller** [comment]
@GabPoll It's always appropriate to comment :) 

We tend not to solicit feedback from you on Pull Requests because they're _mostly_ about code quality - when I do some work then @fredkingham will review the diff in the Files Changed tab here _before_ those changes become part of the code.

This is me proposing the code changes... the next step would be to deploy somewhere, and ask you to review the results. (Though it's always good to hear that we're on the right track based on the descriptions of the changes ! )

**Comment by davidmiller** [comment]
@GabPoll @michaeledwardmarks Do you know what size/model of iPad UCLH buys/uses ? 

That would be useful in directing our efforts...

You two know about the 'Device Mode' in Chrome Developer tools? 
It's very useful in doing this kind of thing:) 

https://developers.google.com/web/updates/2016/03/device-mode-v2?hl=en

**Comment by michaeledwardmarks** [comment]
Interesting. I haven't tried that.
I imagine they buy full size iPad but we can ask.

**Comment by michaeledwardmarks** [comment]
Does the small screen thing let me play about on my laptop as if I had a smaller screen?

**Comment by davidmiller** [comment]
@michaeledwardmarks Precisely. 
In fact, a range of smaller screens preset to the sizes of common devices.
It is good.

**Pull request merged**
